services:
  - type: web
    name: django-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn notes_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: notes_project.settings